-- V31: 전략 상태 CHECK 제약 갱신
-- 기존: DRAFT, ACTIVE, ARCHIVED 만 허용
-- 변경: DRAFT, PENDING_REVIEW, APPROVED, PUBLISHED, REJECTED, ACTIVE, ARCHIVED 허용

ALTER TABLE strategies DROP CONSTRAINT IF EXISTS check_strategy_status;

ALTER TABLE strategies ADD CONSTRAINT check_strategy_status
    CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', 'ACTIVE', 'ARCHIVED'));
